### ISSUE TITLE
Tests not running across machines

### ISSUE THREAD

**Issue by geniuscodemonkey** [AutomateThePlanet/Meissa#10]
I have 3 machines, one server, one worker and one runner.  I get the following error on the Worker and runner...

Test agent with tag APIAgent starts tests execution on machine WORKER.
NUnit Console Runner 3.7.0
Copyright (c) 2017 Charlie Poole, Rob Prouse
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000
Test Files
    C:\Users\XXX\AppData\Local\Temp\7\8fb689fc-f5f4-4318-a9a6-9140c7a56716\TestAutomation.Dashboard.Tests.dll
    C:\Tests\packages\
Errors, Failures and Warnings
1) Invalid : C:\Users\XXX\AppData\Local\Temp\7\8fb689fc-f5f4-4318-a9a6-9140c7a56716\TestAutomation.Dashboard.Tests.dll
File not found: C:\Users\XXX\AppData\Local\Temp\7\8fb689fc-f5f4-4318-a9a6-9140c7a56716\TestAutomation.Dashboard.Tests.dll
2) Invalid : C:\Tests\packages\
File not found: C:\Tests\packages\
Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-10-09 11:15:40Z
    End time: 2018-10-09 11:15:41Z
    Duration: 0.284 seconds
Results (nunit3) saved as C:\Users\XXX\AppData\Local\Temp\7\tmpCC63.tmp
TEST AGENT RUN COMPLETED

**Comment by angelovstanton** [comment]
I think we already solved this over the chat in the latest beta.
