### ISSUE TITLE
Meissa test runner - cannot start execution

### ISSUE THREAD

**Issue by mirceabalan** [AutomateThePlanet/Meissa#11]
Hi, 

I get the following error while trying to execute the test cases with Meissa:
System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]' to type 'System.Collections.Generic.List`1[System.String]'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]' to type 'System.Collections.Generic.List`1[System.String]'.

Do you have any clue what can be the cause of this?
Thanks!

**Comment by angelovstanton** [comment]
I am sorry for my late answer. For some reason I didn't receive any notifications... Usually people just drop me a line in our project chat. I guess you used the official version from the website or you have tried the beta?

**Comment by angelovstanton** [comment]
Hi,

There is a new beta release. Can you try it? It is used in a little bit different way. Now it is installed through .NET CLI through nuget package.

dotnet new -i Meissa.Windows64
dotnet new Meissa.Windows64
dotnet meissa.dll something...
