### ISSUE TITLE
Cannot find file or reference "System.Configuration.ConfigurationManager"

### ISSUE THREAD

**Issue by kamilchodola** [AutomateThePlanet/Meissa#12]
Hello,

I dowloaded latest release version of Meissa and trying to run tests with it. I started srevre and test agent, but when i try to run meissa.exe runner i get exception

System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 

What can i do with this?

**Comment by angelovstanton** [comment]
Hi,

Can you tell me on which operating system you are trying to run the tool?

**Comment by kamilchodola** [comment]
Windows Server 2012R2
Version 6.3 (9600)

**Comment by angelovstanton** [comment]
Have you checked the requirements of the tool and installed the right version of .NET Core? To be honest the tool was tested and previewed to work only against latest Windows 10.

**Comment by kamilchodola** [comment]
I have installed .NET Core Runtime in latest version. Can you tell me which version is right?

**Comment by angelovstanton** [comment]
Can you try with 2.1.503?

**Comment by angelovstanton** [comment]
Also, do you have a machine with different operating system just to test whether it is a problem for Windows Server. I believe this is the case. I have something in mind how we can fix it. The uploaded build was specifically created for Windows 8 and Windows 10 not Server. So, maybe I will have to create a dedicated build for you for Windows Server.

**Comment by kamilchodola** [comment]
Hi,

I installed .Net Core SDK in this version and have same result. 
I downloaded version from this post -> https://github.com/AutomateThePlanet/Meissa/issues/3#issuecomment-380774978 .
This give me other exception: 
"System.AggregateException: One or more errors occurred. (Unable to load one or m
ore of the requested types. Retrieve the LoaderExceptions property for more info
rmation.) ---> System.Reflection.ReflectionTypeLoadException: Unable to load one
 or more of the requested types. Retrieve the LoaderExceptions property for more
 information."
First version which i downloaded was from "Release" tab here on github. Maybe this is the case? I also tried to run it on Windows 8.1 but i have the same result.

**Comment by angelovstanton** [comment]
Can you try to install the new version, it has a slightly different way of installation through .NET Core templates?
First run the bellow, it will download the tool in the local nuget cache.
dotnet new -i Meissa.Windows
Next run the bellow to folder of your choosing and the tool will be extracted and ready to use from there.
dotnet new Meissa.Windows

Next instead of calling meissa.exe --> call
dotnet meissa.dll 
commands after that stay the same

**Comment by kamilchodola** [comment]
THANKS! 
It works perfectly now. Now i just need to configure it and start working :) Star for project :)

**Comment by angelovstanton** [comment]
Perfect! Glad that I could help. :)
I will close this issue, if you have other problems open a new thread.
