### ISSUE TITLE
Nuget package missing

### ISSUE THREAD

**Issue by paynetechnologies** [AutomateThePlanet/Meissa#17]
Hi Anton,
I was attempting to create a plugin needed for xUnit and per the instructions to create a new plugin:

**Steps to Write New Plugin
Create a new C# .NET Core/.NET Standard library project
Install Meissa.Plugins.Contracts NuGet Package**

I go an error message: 

NU1101: Unable to find package Meissa.Core.Model. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
![Nuget package missing error](https://user-images.githubusercontent.com/628590/64202558-6dbf9d80-ce5f-11e9-8a67-6077282a5c7a.png)

Thanks,
Howard

**Comment by angelovstanton** [comment]
Hi Howard,

I pushed the missing nuget.

Can you try it now? 

Let me know if something goes wrong again.

Best,
Anton

**Comment by paynetechnologies** [comment]
Anton,

No longer getting the error and the solution builds OK.

Thank you,
Howard
