### ISSUE TITLE
Meissa.Plugins.Contract

### ISSUE THREAD

**Issue by paynetechnologies** [AutomateThePlanet/Meissa#19]

**Comment by paynetechnologies** [comment]
re: In the How to Develop Plugins:

Steps to Write New Plugin
In step 2, Install Meissa.Plugins.Contracts NuGet Package

The signature for method SplitTestCases from step 2 NuGet Package is different than the existing signature in Meissa-Master/Meissa.Plugins.Contracts. 

Is this correct, by design, or a version difference issue? Which signature should I implement?

From nuget: 
List<TestCase>[] SplitTestCases(List<TestCase> list, int availableCores);


From Meissa-Master/Meissa.Plugin.Contracts:
List<List<TestCase>> SplitTestCases(int availableCores, bool sameMachineByClass, List<TestCase> testCasesToBeDistributed);


Thank you,
Howard

**Comment by angelovstanton** [comment]
Hi Howard,

Sorry for late reply but I was traveling a bit.

I think the right version is:

List<List<TestCase>> SplitTestCases(int availableCores, bool sameMachineByClass, List<TestCase> testCasesToBeDistributed)

this is the code on master from what I see. I redownloaded and regenerated the nuget the version should be the same now.

**Comment by paynetechnologies** [comment]
I will download the updated package.

Thank you so very much.

**Comment by angelovstanton** [comment]
Sorry for my late answer but I was on a vacation last week. I review what happend and the new Core.Model package was missing. I published it as well. Can you try now?

**Comment by paynetechnologies** [comment]
No longer receiving the package downgrade message and building without issues.

Thank you for the update
