### ISSUE TITLE
Question about parameter --timeBased

### ISSUE THREAD

**Issue by FelixBaum** [AutomateThePlanet/Meissa#21]
I have a question for the _--timeBased_ parameter.
If I use this parameter with the _--parallelRun_ parameter, does it sort the tests by runtime?

Does it run the long running tests in parallel first and after them the tests, which are faster?

**Comment by angelovstanton** [comment]
Actually, the idea is that it will collect data about the tests and the time. On the next runs it will use the data to group the tests but equal total time between different processes. There isn't a logic to run the long running first. I hope I managed to answer.
