### ISSUE TITLE
Would it be possible to use Meissa to run tests on cloud browser providers (BrowserStack, SauceLabs, etc)?

### ISSUE THREAD

**Issue by CosminGramada** [AutomateThePlanet/Meissa#7]
I was wondering if it be possible to use Meissa to run tests on cloud browser providers like BrowserStack or SauceLabs?

This could be helpful for projects that have mobile-web tests, or even Native applications.

**Comment by angelovstanton** [comment]
Hey Cosmin,

Meissa is written in a way that it is entirely independent of how your tests work. Meaning that if in your tests you use selenium grid for cloud providers then it will be transferred there. The only thing you have to check is whether your plan can handle the Meissa parallelism. If you need more info or some guidance how to make it work for your case find me on our gitter chat.

Anton

**Comment by angelovstanton** [comment]
Closing the thread now
